CREATE TABLE "USER"
(
   "USER_ID" NUMBER(10,0) NOT NULL auto_increment,
   "USERNAME" VARCHAR2(255 CHAR),
   "PASSWORD" VARCHAR2(32 CHAR),
   "EMAIL" VARCHAR2(255 CHAR),
   "PHONE_NUMBER" VARCHAR2(20 CHAR),

   PRIMARY KEY ("USER_ID")
 );
